[package]
name = "caller"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "caller"

[features]
default = []

[dependencies]
anchor-lang = { workspace = true }
callee = { path = "../callee" }
