# Konfiguracja programu on-chain.
[package]
name = "hello_anchor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "hello_anchor"

[features]
default = []

[dependencies]
anchor-lang = { workspace = true }
