[package]
name = "pda_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pda_example"

[features]
default = []

[dependencies]
anchor-lang = { workspace = true }
